### ISSUE TITLE
Handoff state to new process

### ISSUE THREAD

**Issue by arjan** [derekkraan/horde#13]
Is therea mechanism implemented in this library that a process can hand off its state when the process is being restarted on another node? A bit like what [swarm](https://github.com/bitwalker/swarm/blob/master/README.md#example) has implemented?

**Comment by derekkraan** [comment]
Hi @arjan, I haven't implemented anything like that in Horde.

That's partially because I want to make sure the basics work really well before I start adding more features and also partially because I'm not sure how that would work if you're not running a single layer of processes under Horde. (but maybe this isn't important and such a feature would only work for the single layer of processes under Horde scenario).

**Comment by arjan** [comment]
Thanks for the explanation! I'll stick with Swarm for now then.. ;-) I'll keep an eye out on this project.
