### ISSUE TITLE
Registries not cleaned properly after node crash or shutdown

### ISSUE THREAD

**Issue by mszmurlo** [derekkraan/horde#16]
Hi Derek,

This is an issue on registries.

My `xyz` application actually starts a distributed registry `XYZ.DReg` and a distributed supervisor `XYZ.DSup` in its supervision tree. At boot, it also start a random number of dummy `Task`s so there is a good chance that the pids of same processes running on each node are different (`for i<-1..:rand.uniform(100), do: Task.async(fn -> nil end)`).

The scenario is as follows.

Let's start two nodes (each starting the application) in two terminals:

    ERL_AFLAGS="-name nd1@127.0.0.1 -setcookie abcd" iex -S mix

end

    ERL_AFLAGS="-name nd2@127.0.0.1 -setcookie abcd" iex -S mix

Let's check distributed registry members:

    iex(nd1@127.0.0.1)1> Horde.Cluster.members(XYZ.DReg)
    {:ok, %{"Ef/Vdd/0tI2LWdFuVpVFWg==" => {#PID<0.198.0>, #PID<0.202.0>}}}

and

    iex(nd2@127.0.0.1)1> Horde.Cluster.members(XYZ.DReg)
    {:ok, %{"kAu9t9EZlbteNeJnWMLNZA==" => {#PID<0.197.0>, #PID<0.201.0>}}}

Now, lets join the registry horde from node `nd1` and recheck for members:

    iex(nd1@127.0.0.1)3> Horde.Cluster.join_hordes(XYZ.DReg, {XYZ.DReg, :"nd2@127.0.0.1"})
    true
    iex(nd1@127.0.0.1)4> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       "Ef/Vdd/0tI2LWdFuVpVFWg==" => {#PID<0.198.0>, #PID<0.202.0>},
       "kAu9t9EZlbteNeJnWMLNZA==" => {#PID<16274.197.0>, #PID<16274.201.0>}
     }}

and on `nd2`:

    iex(nd2@127.0.0.1)2> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       "Ef/Vdd/0tI2LWdFuVpVFWg==" => {#PID<16320.198.0>, #PID<16320.202.0>},
       "kAu9t9EZlbteNeJnWMLNZA==" => {#PID<0.197.0>, #PID<0.201.0>}
     }}

Things are looking good for a normal situation. So let's kill node `nd2` (or shutdown it with `:init.stop`) and recheck for members on `nd1`:

    iex(nd1@127.0.0.1)5> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       "Ef/Vdd/0tI2LWdFuVpVFWg==" => {#PID<0.198.0>, #PID<0.202.0>},
       "kAu9t9EZlbteNeJnWMLNZA==" => {#PID<16274.197.0>, #PID<16274.201.0>}
     }}

The reference to the registry that was running on the dead node is still present. If you join a third node `nd3` to the cluster and to the `XYZ.DReg` horde, it will be propagated as well.  I believe it will have an impact if one alive node tries to sync with this dead node.

Cheers
Maurycy

**Comment by derekkraan** [comment]
Hi, thanks again for taking the time to test.

This is an issue that I'll have to take a look at soon. Right now it's only possible to add a neighbour to the CRDT that's backing `Horde.Registry` and `Horde.Supervisor`. This will indeed cause problems at the CRDT level because the CRDT will try (and be unable) to sync with all its neighbours. That's not a problem in and of itself but it means that delta GC won't function properly, eventually causing a memory leak.

At the Registry level it shouldn't cause any problems though.

Derek

**Comment by shifters67** [comment]
Hi Derek,
also seeing this when a node is shutdown (via CTRL-C or a crash etc),  All the pids that were registered by the shutdown node are still in the registry on the other hosts and it seems to be permanent i.e. not a timing issue.  It seems that the registries never get cleaned up.

Running Horde.Registry.processes(Horde.LocalRegistry) shows the processes including the  failed ones on the shutdown/crashed node.  When you do a  Horde.Registry.lookup of the name then you get :undefined.  Seems a bit inconsistent?

As i trap node_up and node_down events i guess it could be used to unregister the pids for any processes on the failed node - is there an easy way to select these from the local registry?

As an aside - registry does not support process groups which would be helpful (and could be used e.g. to select all processes on node X when node X fails if for example all pids were put in auto groups of the node name - I would then catch the node_down and clear the registry of dead pids) - sorry for rambling - just thinking!

Your thoughts?

Cheers
Tom

**Comment by derekkraan** [comment]
Hi @shifters67,

The registries never get cleaned up, that's correct. I believe this is also current behaviour for the standard library Registry. Also like the stdlib Registry, when doing a lookup, we return `:undefined` when the process is dead.

The stdlib Registry doesn't have a `processes/1` function. So one option is to remove that from the public API of Horde.Registry. Checking each process when one calls `processes/1` would make that function slow, so that's not really a good option.

There is also no local state, all state is global, so also no easy way (aside from using `Enum.filter` in combination with `node/1`) to find out which pids have come from which nodes.

If I understand correctly, the real problem is that `Horde.Registry.processes` is returning dead processes(?).

The pub/sub / dispatch functionality in the stdlib Registry is based on `duplicate` registries, while we only support `unique`. So this is a bit of a stretch goal at the moment (but certainly possible with a CRDT).

Back to the possible solution though, what are you using `Horde.Registry.processes/1` for? Can you give me some more information on that?

**Comment by derekkraan** [comment]
Closing in favour of #31.
