### ISSUE TITLE
Add documentation on how to handle process handoff after netsplit / conflict a la Swarm

### ISSUE THREAD

**Issue by hubertlepicki** [derekkraan/horde#161]
I was struggling to find information on how to recover after a netsplit in a way that allows the state to be merged between conflicting processes.

My use case is that I am running a bunch of counters, and whenever netsplit occurs, these keep being updated independently. Then, Horde would kill one of the processes, leaving the other counter not fully updated.

I want to implement a state handoff, where process being killed passes it's state to the winning process. I can see I can implement it with adding the callback to handle `:name_conflict` and send a message containing the state being handed off to the `winning_pid`.

https://github.com/derekkraan/horde/blob/1011e98be05e76363602782b6b1cfd155dc56f1d/lib/horde/registry.ex#L201

1. Is this the correct approach of doing things?
2. Can I add a documentation page describing the above? I was really confused about Horde not having the idea of resolving the processes handoffs like Swarm does, which led me to choose Swarm over Horde in a project, something that I am in the middle of reverting because of other technical issues with Swarm.

**Comment by derekkraan** [comment]
Your approach sounds reasonable.

I think this page in the docs is what you're looking for: https://hexdocs.pm/horde/eventual_consistency.html#content

If you have ideas on how to make it easier to find this page or ideas on how to improve this page, I will definitely accept a PR. If you don't think this is the page you were looking for, feel free to do whatever you can to improve the docs so that it does address your concerns.

**Comment by derekkraan** [comment]
Closing this, but feel free to re-open if you feel that the issue still needs addressing.
