### ISSUE TITLE
Issues adding Horde.Registry or Horde.Supervisor to application supervision tree

### ISSUE THREAD

**Issue by shifters67** [derekkraan/horde#20]
Hi Derek,

Still struggling with this.  I can run the hello_world example fine but when i try and incorporate Horde.Registry or Horde.Supervisor in my own application supervision tree i get the following error:

** (Mix) Could not start application core: Core.Application.start(:normal, []) returned an error: shutdown: failed to start child: Horde.LocalRegistry
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Keyword.get/3
            (elixir) lib/keyword.ex:179: Keyword.get({#PID<0.186.0>, :members_updated}, :notify, nil)
            (delta_crdt) lib/delta_crdt/causal_crdt.ex:64: DeltaCrdt.CausalCrdt.start_link/3
            (horde) lib/horde/registry.ex:141: Horde.Registry.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

The Code being run to try and do this is:

  def start(_type, _args) do
    import Supervisor.Spec

    # List all child processes to be supervised
    children = [
      %{
          id: Phoenix.PubSub.PG2.Dalek.Core,
          start: {Phoenix.PubSub.PG2, :start_link, [:core, []]}
      },
      {Horde.Registry, [name: Horde.LocalRegistry]},
      {Horde.Supervisor, [name: Horde.LocalSupervisor, strategy: :one_for_one]},
      worker(Core.Scheduler, []),

etc with other children

Removing the Horde child processes and all is fine, but adding those causes the error above.  I am obviously using it wrong but 3 hours spent trying to work out why is making me pull my hair out!

Any help greatly received as Horde (rather than Swarm) is exactly the functionality i am looking for.

Tom

**Comment by derekkraan** [comment]
Hi Tom,

You are in fact doing nothing wrong. This is a cautionary tale of what happens when semantic versioning isn't properly observed.

In other words, I have released a version of `delta_crdt` which is incompatible with the previous version and only incremented the minor version number, causing an incompatible version to match with the version specification in previous packages of `horde`.

I will be releasing a new version of `horde` shortly which fixes this problem (and keeping a much closer eye on package versioning from now on). Until then, you should be able to continue forward with the following package spec in your `mix.exs`: `{:horde, github: "derekkraan/horde"}`

Cheers,
Derek

(PS, I'm closing this because there's nothing I can do aside from releasing a new version that fixes this problem but feel free to open a new issue if you run into anything else. Thanks!)
