### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by deadtrickster** [derekkraan/horde#200]
Reposting from ElixirForum (https://elixirforum.com/t/horde-memory-usage/30849)

Hello,

We are using Horde to have “about one” process for a key in a cluster. We poll external service and each run we ask Horde to start a process with a key. If we already saw the key, Horde reports already_started as expected. However, we observe that internal merkle_map grows linearly with startup attempts.

crdt_size = fn ->
  pid = Process.whereis(Elixir.MyHordeSupervisor.Crdt)
  state = :sys.get_state(pid)
  map_size(Map.get(state, :merkle_map).map)
end

iex(9)> crdt_size.()
10077
iex(11)> crdt_size.()
10077
iex(12)> Enum.each(1..10000, fn _ -> start_constant_queue.() end)
:ok
iex(13)> crdt_size.()                                            
20079
iex(15)> Enum.each(1..10000, fn _ -> start_constant_queue.() end)
:ok
iex(16)> crdt_size.()                                            
30081
depending on number of keys and refresh rate memory limit hit pretty quickly.
Elixir.MyHordeSupervisor.Crdt process memory size will be hundreds of megabytes.

While writing code we following the docs on hexdocs.       

Any help would be appreciated. Thanks!

EDIT: 

I also switched from Horde registry to syn (in :via tuples). 

Same result - e.g. Elixir.MyHordeSupervisor.Crdt consumes 193 megabytes.

**Comment by derekkraan** [comment]
Hi @deadtrickster,

Thanks for reporting this issue. Can you give me some more information? An example app that I can use to reproduce the issue (or spot the problem with your code) would be ideal. At the very least, I need to see your supervisor code and the `start_constant_queue()` function.

**Comment by deadtrickster** [comment]
@amamla ^^

**Comment by amamla** [comment]
Hi @derekkraan 

We have actually tracked down the source of the issue in our code. It was caused by a slight modification in the function that was starting the particular worker:

```
def start_link(opts = %{:name => name}) do
    case GenServer.start_link(__MODULE__, opts, name: via_tuple(name)) do
      {:ok, pid} ->
        {:ok, pid}

      {:error, {:already_started, pid}} ->
        # this is the part that causes leak
        {:ok, pid}

        # :ignore
    end
  end
```
So returning `{:ok, pid}` instead of `:ignore` for already running process. Although it was an error on our side it shows quite an unexpected vulnerability in Horde.

I've [forked Horde and introduced some changes](https://github.com/amamla/horde/tree/memory_leak_investigation/examples/hello_world) in the `hello_world` example to be able to reproduce the issue. Once you start the `hello_world` example  from my fork (single node is enough to reproduce it)
`iex --name count1@127.0.0.1 --cookie asdf -S mix`
you can run the simulation of memory leak with this:
`HelloWorld.LeakRunner.repeat(30, 200, 5000)`
this will run 30 attempts to start 200 processes via Horde, waiting 5000ms between each next attempt.
No matter the number of repeats the total count of started processes should be constant:
```
iex(count1@127.0.0.1)2> HelloWorld.Leak.count()
200
```
so this behaves as expected. But after each  attempt the runner will print the total heap memory used by horde-related processes. Here are the results after first run of 
```
iex(count1@127.0.0.1)1> HelloWorld.LeakRunner.repeat(30, 200, 5000)
(...)
    Elixir.HelloWorld.HelloSupervisor.Crdt                9.127MB
    Elixir.HelloWorld.HelloSupervisor.ProcessesSupervisor 1.719MB
    Elixir.HelloWorld.HelloSupervisor                     9.131MB
```
and after total of 90 repeats:
```
    Elixir.HelloWorld.HelloSupervisor.Crdt                26.701MB
    Elixir.HelloWorld.HelloSupervisor.ProcessesSupervisor 7.283MB
    Elixir.HelloWorld.HelloSupervisor                     12.486MB
```
and growth of memory consumption continues with next attempts.

Although this is related to incorrect return type, it seems that Elixir's `DynamicSupervisor` is resilient to it:
```
iex(count1@127.0.0.1)3> HelloWorld.LeakRunner.init_dynamic_sup()
(...)
iex(count1@127.0.0.1)4> HelloWorld.LeakRunner.repeat_dynamic_sup(90, 200, 2000)
(...)
MyApp.DynamicSupervisor 0.167MB
```
Example above runs the same broken module through `DynamicSupervisor` but is able to handle the lack of `:ignore` for already started processes.

**Comment by szlend** [comment]
Tbh, isn't it conceptually wrong to return `{:ok, pid}` in `start_link/1` for a process that already existed beforehand? It's sort of a standard interface for starting processes and it shouldn't be doing anything else. I would move whatever you are doing there to your `start/1` function and see if this is still case.

**Comment by amamla** [comment]
@szlend yes, I'm aware that returned value was invalid and I've already stated that it was an issue with our code. And I'm not expecting the process to be supervised twice. 

My point was that if Horde is able to correctly recognize that process should not be started again (see my example, number of started processes is constant and as expected) but the memory consumption grows there is something possibly dangerous happening under the hood.

**Comment by derekkraan** [comment]
@amamla have you tried returning `:ignore` instead of `{:ok, pid}`? See this section of the docs for more details: https://hexdocs.pm/horde/eventual_consistency.html#horde-dynamicsupervisor-merge-conflict

**Comment by derekkraan** [comment]
For what it's worth, I think @szlend hit it on the head. Returning `{:ok, pid}` will cause `pid` to be supervised again. You don't want to supervise a process twice, it can lead to some very strange situations.

**Comment by szlend** [comment]
@amamla the decision not to start the process is performed by the registry and the supervisor doesn't know anything about that. That's why the process count in your example stays constant. The supervisor will gladly supervise anything you give it. It might be possible for the supervisor to check if it's already supervising a process. Though that won't help if you pass it a process monitored by another supervisor on another node.

**Comment by amamla** [comment]
I think we can close this one in that case. Thanks for your replies.
