### ISSUE TITLE
Strange Behavior with `:via` tuple when starting and quickly using a process.

### ISSUE THREAD

**Issue by jeffutter** [derekkraan/horde#214]
I'm running into a strange issue when starting and immediately trying to use a process using `:via` tuples.

I'm trying to start a dynamically supervised `:gen_statem` with a `start_link` like this:

```
  def start_link(opts) do
    name = opts[:name]

    case :gen_statem.start_link({:via, HordeRegistry, {MyHordeRegistry, name}}, __MODULE__, opts, []) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, _pid}} -> :ignore
    end
  end
```

The issue I'm seeing is that the process starts fine. However, if it starts on another node I end up being unable to access it from the first node. I think this is somewhat related to the Registry CRDT syncing. I added some debugging to the `whereis_name`, `register_name`, and `unregister_name` functions in `Horde.Registry`.

With that we get some picture of what is happening (the first bit of the logs is the node name):

```
> Node.self()
:"buffer-test11@127.0.0.1"

> Horde.DynamicSupervisor.start_child(MyHordeSupervisor, child_spec(name: :test))

WhereisName, {:"buffer-test12@127.0.0.1", MyHordeRegistry, :test}: :undefined
RegisterName: {:"buffer-test12@127.0.0.1", MyHordeRegistry, :test, #PID<0.713.0>}: :yes
WhereisName, {:"buffer-test12@127.0.0.1", MyHordeRegistry, :test}: #PID<0.713.0>

{:ok, #PID<0.713.0>} # The process was started ok, great!

> Node.self()
:"buffer-test11@127.0.0.1"

> :gen_statem.call({:via, HordeRegistry, {MyHordeRegistry, name}, %{})

WhereisName, {:"buffer-test11@127.0.0.1", MyHordeRegistry, :test}: :undefined

{:badrpc, {:EXIT, {:noproc, {:gen_statem, :call, [{:via, Horde.Registry, {MyHordeRegistry, :test}}, %{event: :list, trace_ctx: nil}, :infinity]}}}}
```

Any type of `HordeRegistry.lookup` or anything like that at this point, for that process returns no results.

This creates a particularly interesting problem when you have a `start_or_find` type function using `Horde.Registry.whereis_name`. The first time you run it works great starting the process returns the PID. But the second time you run it starting fails (because the process exists and `start_link` returns `:ignore`) and then the `find` fails because it looks for the process in the `Registry` and it hasn't replicated yet.

Interestingly I sort of ran backward into the problem mentioned in https://github.com/derekkraan/horde/issues/200

If I have the `start_link` return the `pid` form `{:error, {:already_started, _pid}} ` I'm able to use that to find the process, but I realize that causes other problems.

It is very likely that I'm doing something wrong here or misusing the library but any suggestions would be appreciated.

Please let me know if you need any more info or if an example repo would be helpful.

Thanks!

**Comment by derekkraan** [comment]
Hi @jeffutter,

Yes, fundamentally Horde works on the principle of "eventual consistency", so there is no guarantee that you will be able to see your new process from all nodes "immediately" (including the node on which you requested starting the new process from, if it was in fact started on a remote node).

The solution is to adjust your system so that you can handle eventual consistency gracefully, or switch to a system that employs immediate consistency (but which will likely be slower).

I think this answers your question. If I understand correctly, this is a transient condition that resolves when the underlying CRDT has had enough time to sync values across the cluster. Please re-open if this is not the case.

Cheers,
Derek

**Comment by jeffutter** [comment]
@derekkraan yeah. I think that is essentially it. The part that is somewhat unexpected is that the Registry says “nope, that process doesn’t exist” while the supervisor says “that process already exists, but I can’t tell you where and you can’t start a new one”.

I’m guessing that this scenario only happens if the supervisor picks the node it already started on and the registry hasn’t propagated yet. It’s probably possible it could pick another node and it would start a duplicate which would eventually be killed with a name collision - this I would expect.

**Comment by derekkraan** [comment]
Because the default strategy is to predictably choose the same node every time for a particular process, the request to start a process will come in to the same node again the second time, and the Registry (not Horde.DynamicSupervisor) says no.

You _could_ use the Horde.DistributionStrategy to predict where a process should be and try to find it there. That will only be useful for mitigation, however, there is still no guarantee that this will work under all conditions (eg: changing cluster membership).

**Comment by markmeeus** [comment]
Yes, this behaviour is indeed a bit confusing at first. 

We worked around this quirk with a simple sleep-and-retry mechanism. 

First we make sure the process is definitely started.
Then we try a few times to obtain it's pid via the registry, eventually we'll get it.

Would it make sense to have this pattern somewhere documented?

**Comment by derekkraan** [comment]
Yes, retries are an important strategy in dealing with this kind of a scenario. How do you make sure the process is definitely started though? In order to do that you need to have the pid, and if you have the pid then you have the pid, right?
