### ISSUE TITLE
GenServer.cast cant find process via {:via, Horde.Registry, ...}

### ISSUE THREAD

**Issue by Ellocsys** [derekkraan/horde#248]
Hi!
`GenServer.cast/2` cant find process via `{:via, Horde.Registry, ...} `
In case cast using pid everything works ok
I prepared a small test to explain the problem

``` Elixir
defmodule HordeTest do
  use ExUnit.Case

  test "via with cast" do
    horde = start_registry()

    name = {:via, Horde.Registry, {horde, "foo", %{data: "data"}}}

    {:ok, pid} = Agent.start_link(fn -> 0 end, name: name)

    assert Agent.cast(name, &(&1 + 1)) == :ok

    assert Agent.cast(pid, &(&1 + 3)) == :ok

    Process.sleep(100)

    # Fail because Agent returns 3
    assert Agent.get(name, & &1) == 4
  end

  defp start_registry(opts \\ [keys: :unique]) do
    horde = :"h#{-:erlang.monotonic_time()}"

    {:ok, _pid} =
      Horde.Registry.start_link([name: horde, delta_crdt_options: [sync_interval: 20]] ++ opts)

    horde
  end
end
```

Is this behaviour would be a bug?

Horde: 0.8.6
Elixir: 1.12.3
Erlang: 24.1.6

**Comment by smaximov** [comment]
@derekkraan, looks like it does:

```elixir
agent() :: pid() | {atom(), node()} | name()
name() :: atom() | {:global, term()} | {:via, module(), term()}
```

i.e. `agent()` &rarr; `name()` &rarr; `{:via, module(), term()}`

**Comment by smaximov** [comment]
So we investigated a little and found that my example works because the via tuple doesn't contain any metadata; and removing the metadata from the via tuple when casting the agent process fixes the original test. Changing `Horde.Registry` to `Registry` doesn't seem to make any difference, so it's probably not a Horde issue.

The interesting thing is that changing `Agent.cast/2` to `Agent.call/2` works regardless using metadata in the via tuple. I've [opened an issue](https://github.com/elixir-lang/elixir/issues/11740) in the Elixir's repo if you are interested in details.

**Comment by derekkraan** [comment]
Great thanks for looking into this!
