### ISSUE TITLE
Is there a way to leave a process where it is when topology changes?

### ISSUE THREAD

**Issue by rubberduck203** [derekkraan/horde#32]
First I’d like to say that this is great work. 
I spent several days with Swarm before realizing it didn’t fit my needs because it doesn’t supervise processes. 
Being Horde allows proper distributed supervision of sub trees, it seems to meet my needs perfectly, so thank you!

On to the real question...

Maybe I’m missing an option somewhere, but I can’t seem to find a way to tell Horde to leave processes running where ever they currently are when a node is added to the cluster. 
I’m currently seeing the following behavior:

- Bring node A online
- App starts, supervision trees added to Horde
- All `:ok`
- Bring node B online
- App starts, moves currently running processes to node B

It would be nice if I could leave those processes running on node A. 

I’m using Horde so that I can have a hot standby node ready to take over should node A leave the cluster unexpectedly. 
That works, but the current behavior means there is a tiny bit of instability when my failover node comes online, or anytime one of my containers gets restarted really.

**Comment by derekkraan** [comment]
Hi Christopher,

Good to hear that Horde is a good fit!

It sounds like you might be adding the supervision trees to Horde on node B
before joining with the Horde instance on node A. In this case, horde's
conflict resolution will kick in and it'll choose the newest (aka the
processes on node B) and shut them down on node A.

Other than that, Horde does not actively move processes around when
topology is changing. So the only thing you could be seeing here is
conflict resolution.

Let me know of this is the issue so I can close this ticket.

Cheers
Derek

**Comment by derekkraan** [comment]
Actually your code looks good to me. I realized where the problem is
though. `Horde.Cluster.join/2` waits until the two hordes know about each
other but their data isn't necessarily synced yet. The gears are grinding a
bit in my head on how we can maybe fix this, but until then you should be
able to patch over this problem by putting a `Process.sleep(100)` before
`Horde.Supervisor.start_child/2`.

**Comment by derekkraan** [comment]
Hmm, after having looked a little bit closer at the code, I actually don't think there is an easy way to fix this. Horde is inherently eventually consistent, and there is no way to tell at any particular moment whether a particular node has gotten all updates (in this case, updates about which nodes are in the horde). The best you can do in this case is calculate a reasonable time to wait for Horde to sync up, taking into account network latency in your particular situation and Horde's internal ship intervals (for horde membership, that's 5ms). With 50 or 100ms chances are really good that the local (new) instance of Horde.Supervisor will know about the other nodes in the network which will prevent it from starting these instances incorrectly locally.

Hope this helps! I think I will have to add a section to the documentation dealing with this particular case, because I think a lot of people will end up running into this.

**Comment by derekkraan** [comment]
Which version of delta_crdt are you using? This new error should be solved
in the latest version.

I'm not sure why the fix would work for connecting Node B but not for
reconnecting Node A. Do you have any logs you can share that might shed
some light on the issue?

**Comment by rubberduck203** [comment]
I’m going to go ahead and close this as “by design”. Understanding that it’s an eventually consistent system really helped. I do *wish* the consistency algorithm could choose the oldest of the two running processes, but it really is a wish not a need. 

Thanks for the help and the great library!

**Comment by derekkraan** [comment]
I mean, it might be something to consider. The choice to go for the newest
one is definitely up for discussion, and it seems like it would help this
use case quite a bit.

**Comment by rubberduck203** [comment]
I don’t have enough insight into other people’s use cases to say what the right thing is.

**Comment by dowusu** [comment]
I hope I'm not too late to the party, I've been used horde for a while and currently experiencing the above issue. I'm connecting to an upstream SMSC server and anytime a new node joins the cluster, I temporarily lose binding to server.
Is there any workaround for this issue. Great work by the way.
