### ISSUE TITLE
Update example application to better illustrate correct start-up procedure.

### ISSUE THREAD

**Issue by derekkraan** [derekkraan/horde#52]
The current example app uses `start_child` before the cluster has been formed, resulting in "hijacking" the process whenever a new node is added. I'd like to change this to show the more correct flow of first connecting to the cluster and only then starting the child process(es).

**Comment by chazsconi** [comment]
@derekkraan Would you be able write down in this issue a quick summary of what you think the correct flow should be with both distribution strategies.

I'm using `Horde.UniformQuorumDistribution` to ensure my processes really are singletons, therefore I have a slightly different problem in that the processes cannot start at all initially due to lack of quorum.

Therefore my approach, which may not be correct, is to do the following in the `Application.start/2` callback:
1. Start the Horde Registry and Horde Supervisor as children of the application Supervisor
2. Before returning from the `Application.start` try to call `Horde.Supervisor.start_child/2` for all the children.  As this can initially return `{:error, :quorum_not_met}` I therefore enter a retry loop which should eventually succeed once a sufficient number of other nodes have started and joined.  (I guess I could also spawn a task to do this as another child of the top level supervisor, similar to how it is done in the example app).

**Comment by derekkraan** [comment]
This has got me thinking that it might not be a bad idea to offer a function like `wait_for_quorum`, for exactly these cases.

Otherwise, sounds like a reasonable thing to do.

**Comment by chazsconi** [comment]
Thanks for the info.  And yes, having a `wait_for_quorum` function would definitely be useful.

**Comment by meox** [comment]
please upgrade the example

**Comment by derekkraan** [comment]
@meox I have already added `Horde.Supervisor.wait_for_quorum/2` and it's also used in the example app. Thanks for reminding me, now I can close this issue :+1:
