### ISSUE TITLE
Basic code snipets in the documentation

### ISSUE THREAD

**Issue by mszmurlo** [derekkraan/horde#9]
Hi,

This is not that much an issue but rather a doc improvement or completion request.

I wanted to give a try to Horde, after having spent some time with Swarm. I'm not very much  experimented with distributed development in Elixir but I'm not an Elixir newbie. I got quite quickly stuck when trying to define both a Registry and a Supervisor: how to register a worker that is going to be supervised at the same time ? Do I need to use a `:via` tuple or is there some other way ? What about `join()`: should it be executed on each node or is it to be used in case we have  several supervisors/registries? How to start multiple nodes and create a globally distributed supervisor/registry? Etc..

As I believe I'm not the only person in this situation, I think some code snippets with basic patterns would be really helpful. For example:

* start a distributed supervisor
* start a distributed registry
* start a distributed supervisor/registry
* do the same on 2 or 3 nodes to show required configurations and how it works 

Thanks in advance

**Comment by derekkraan** [comment]
Thanks for taking the time to write up an issue about where you are getting stuck / where you think the documentation could be improved. I'll respond to your issues here and if you think the examples are good then I'll incorporate them into the documentation.

`join_hordes()` is associative, so if you have three nodes and run:
```elixir
Horde.Cluster.join_hordes(horde_1, horde_2)
Horde.Cluster.join_hordes(horde_2, horde_3)
```
then all three nodes will operate as one cluster. In effect, node 2 will tell node 1 and node 3 about each other. This is also mentioned [here](https://hexdocs.pm/horde/Horde.Cluster.html) but I think I will change this part of the documentation to make this more explicit.

Combining a Registry and a Supervisor: using the `:via` tuple is the easiest way. You could also call `Horde.Registry.register_name/2` in the `init` callback of any worker you implement. As far as I can tell there is no difference between how you're able to use `Registry` and how you're able to use `Horde.Registry`.

Starting multiple nodes: do you mean how to start multiple Erlang nodes? I haven't mentioned anything about Erlang clustering in the documentation, if this is a point you think could use some more attention then it sounds like I should write a tutorial to help people get up and running from 0 to a distributed Erlang cluster with Horde running a distributed supervisor + registry.

Horde is a work in progress, so thanks for taking time to write down your thoughts. It helps a lot since it's hard to think about what it's like trying to use Horde for the first time if you've just spent a couple of weeks deep in the weeds of implementing the library yourself.

**Comment by derekkraan** [comment]
I've also added an example app that you can take a look at in examples/hello_world.

**Comment by derekkraan** [comment]
I've started on a little tutorial but that'll take a little longer, I hope to have it up this week sometime.

**Comment by mszmurlo** [comment]
Hi Derek,

Thanks for the hello world. It clarified the way to have it work properly.
Usually, when I try new things, I use to write down some notes for my self. I'll let you know If I come with something more than basic notes.

**Comment by derekkraan** [comment]
Hi,

I've spent some time writing a "getting started" guide. I haven't published it yet but I'll drop the link here now so you can take a look at it. If you end up reading it I'd be very interested to know what you think could be improved so that I can make it into a good guide before I publish it.

https://medium.com/@derek.kraan2/getting-started-with-hordes-distributed-supervisor-registry-f3017208e1ce

**Comment by mszmurlo** [comment]
Thanks!  I'll give you feedback by tomorrow.

**Comment by mszmurlo** [comment]
Hi,

Just finished the reading. Nice work, clear and entertaining: that's what I had in mind when I first wrote you about a guide. I would classify it as a middle entry level as all experiments are left for the reader. That's fine for a quick tutorial. For an in depth guide, I would have included more interactivity: commands typed in the repl and the outputs and showing correct results but also the incorrect ones with the explanations of the reasons of the errors. But this is another work...

**Comment by derekkraan** [comment]
Thanks for the feedback, much appreciated!
