### ISSUE TITLE
Subtractive changes to the Horde memberships aren't mirrored in the Registry and Supervisor

### ISSUE THREAD

**Issue by frekw** [derekkraan/horde#94]
Please see: https://asciinema.org/a/lOdfe5xgtt7PO7Qwynu8THKru

If two nodes have been part of the same Horde, PIDs that run on nodes that were part of the previous overlay network configuration are still considered valid. However, if an actual netsplit occurs, the process will be restarted on a node using the new configuration.

I would have expected cluster membership changes to be treated the same as a netsplit, i.e the process to have been started on the other node as well as soon as the Horde memberships were reconfigured.

**Comment by derekkraan** [comment]
Thanks for the bug report.

There is currently no good way to "split" a cluster like this. Using `set_members/2` is not / will not be a good way to do this because these changes are propagated to all members (including the member you are trying to remove) due to the networked nature of the delta crdt. In other words, in a multi-node setup, even if we remove the member in question from our local delta crdt's neighbours list, it will still be propagated via the other members in the system to the member we are trying to remove.

So I will consider this a request for new functionality.

**Comment by derekkraan** [comment]
I figured out what's going on here.

It boils down to the fact that we don't remove processes from the registry if the node has gone away (because it could just be a netsplit). We *do* however allow these to be overwritten.

So when you set the members to just `[2]`, the process in the registry is still addressable, and therefore if you ask it for the process, it will happily give it to you.

When Supervisor tries to start the process (which it does, correctly), it is using the via tuple, so underwater it is checking in the registry if that process has already been registered. The Registry says it has, so GenServer returns `{:error, :already_started}`.

So the basic problem is that Registry does not throw away processes, and always returns the process if it can be found. Supervisor is working correctly.
